# Parámetros por defecto para el sistema de trading cuantitativo
# Valores razonables basados en liquidez y simplicidad

# Capital y apalancamiento
capital_inicial: 1000000  # USD
apalancamiento_max: 3  # 3:1

# Universo de instrumentos (líquidos y diversificados)
instrumentos:
  indices:
    - "SPY"  # S&P 500 ETF
    - "QQQ"  # NASDAQ ETF
    - "IWM"  # Russell 2000 ETF
  fx_majors:
    - "EURUSD"
    - "GBPUSD"
    - "USDJPY"
  commodities:
    - "GLD"  # Gold ETF
    - "USO"  # Oil ETF
  crypto:
    - "BTC-USD"
    - "ETH-USD"

# Timeframes y ventana histórica
timeframes:
  principal: "1H"  # 1 hora
  secundario: "4H"  # 4 horas
  largo_plazo: "1D"  # Diario

zona_horaria: "UTC"
ventana_historica_anos: 5

# Costos de trading
costos:
  comision_bps: 2  # 2 basis points
  slippage_modelo: "volatilidad"  # bps por volatilidad
  slippage_base_bps: 1
  fees_nocturnos: false

# Restricciones de órdenes
ordenes:
  tipos: ["market", "limit", "stop"]
  tamaño_minimo: 100  # USD
  latencia_max_ms: 100

# Jurisdicción y regulaciones
jurisdiccion: "US"
regulaciones:
  - "SEC"
  - "FINRA"

# Objetivos de riesgo
vol_objetivo_anualizada: 0.15  # 15% volatilidad anual
position_sizing_max_pct: 5  # 5% del capital por trade
max_daily_loss_pct: 2  # 2% pérdida diaria máxima
max_drawdown_pct: 10  # 10% drawdown máximo
exposicion_por_activo_pct: 20  # 20% exposición máxima por activo
exposicion_por_factor_pct: 30  # 30% exposición máxima por factor

# Criterios de aprobación
criterios_aprobacion:
  sharpe_minimo: 1.5
  max_drawdown_maximo: 0.10
  profit_factor_minimo: 1.3
  hit_ratio_minimo: 0.45

# Configuración de backtesting
backtesting:
  train_pct: 0.6
  validation_pct: 0.2
  test_pct: 0.2
  walk_forward_periods: 12  # meses
  cv_folds: 5
  purged_days: 5  # días de purga entre folds

# Configuración de modelos
modelos:
  baseline:
    momentum_periods: [5, 10, 20, 50]
    mean_reversion_periods: [5, 10, 20]
    volatility_filter_periods: [20, 50]
  
  ml:
    lasso_alpha_range: [0.001, 0.01, 0.1, 1.0]
    xgboost_params:
      max_depth: [3, 6, 9]
      learning_rate: [0.01, 0.1, 0.3]
      n_estimators: [100, 300, 500]
    ensemble_methods: ["voting", "stacking"]

# Configuración de monitoreo
monitoreo:
  metricas_diarias:
    - "pnl"
    - "drawdown"
    - "volatilidad_realizada"
    - "sharpe_rolling"
  alertas:
    - "max_drawdown_exceeded"
    - "volatility_spike"
    - "correlation_breakdown"
    - "data_drift"
  kill_switch_triggers:
    - "daily_loss_exceeded"
    - "max_drawdown_exceeded"
    - "data_quality_issues"

